// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  findMaxSum() — copy row with the largest row-sum
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: 6x5 matrix — row 4 has max sum 40 -> [8,8,7,8,9]", "[T1]")
{
    int numbers[6][NUM_COLS] = {{2, 7, 9, 6, 4},
                                {6, 1, 8, 10, 4},
                                {4, 3, 7, 2, 9},
                                {9, 9, 0, 3, 1},
                                {8, 8, 7, 8, 9},
                                {1, 2, 1, 2, 3}};
    int result[SIZE] = {0};
    findMaxSum(result, numbers, 6, NUM_COLS);
    int exp[] = {8, 8, 7, 8, 9};
    for (int i = 0; i < 5; i++) REQUIRE(result[i] == exp[i]);
}

TEST_CASE("T1b: 3x5 matrix — row 1 has max sum, copied to result", "[T1]")
{
    // row sums: 5, 50, 15 → row 1 wins
    int numbers[3][NUM_COLS] = {{1, 1, 1, 1, 1},
                                {10, 10, 10, 10, 10},
                                {3, 3, 3, 3, 3}};
    int result[SIZE] = {0};
    findMaxSum(result, numbers, 3, NUM_COLS);
    for (int i = 0; i < 5; i++) REQUIRE(result[i] == 10);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  findMaxElm() — per-row maximum element
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: 6x5 matrix per-row max -> [9,10,9,9,9,3]", "[T2]")
{
    int numbers[6][NUM_COLS] = {{2, 7, 9, 6, 4},
                                {6, 1, 8, 10, 4},
                                {4, 3, 7, 2, 9},
                                {9, 9, 0, 3, 1},
                                {8, 8, 7, 8, 9},
                                {1, 2, 1, 2, 3}};
    int result[SIZE] = {0};
    findMaxElm(result, numbers, 6, NUM_COLS);
    int exp[] = {9, 10, 9, 9, 9, 3};
    for (int i = 0; i < 6; i++) REQUIRE(result[i] == exp[i]);
}

TEST_CASE("T2b: 4x5 matrix per-row max", "[T2]")
{
    int numbers[4][NUM_COLS] = {{1, 5, 3, 2, 4},
                                {7, 7, 7, 7, 7},
                                {0, -1, 9, 2, 5},
                                {100, 50, 25, 75, 12}};
    int result[SIZE] = {0};
    findMaxElm(result, numbers, 4, NUM_COLS);
    REQUIRE(result[0] == 5);
    REQUIRE(result[1] == 7);
    REQUIRE(result[2] == 9);
    REQUIRE(result[3] == 100);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  findMaxVal() — copy the row that contains the global max value
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: 6x5 matrix — row 1 holds value 10 -> [6,1,8,10,4]", "[T3]")
{
    int numbers[6][NUM_COLS] = {{2, 7, 9, 6, 4},
                                {6, 1, 8, 10, 4},
                                {4, 3, 7, 2, 9},
                                {9, 9, 0, 3, 1},
                                {8, 8, 7, 8, 9},
                                {1, 2, 1, 2, 3}};
    int result[SIZE] = {0};
    findMaxVal(result, numbers, 6, NUM_COLS);
    int exp[] = {6, 1, 8, 10, 4};
    for (int i = 0; i < 5; i++) REQUIRE(result[i] == exp[i]);
}

TEST_CASE("T3b: 3x5 matrix — row 2 holds value 99 -> [3,1,99,2,4]", "[T3]")
{
    int numbers[3][NUM_COLS] = {{5, 5, 5, 5, 5},
                                {6, 6, 6, 6, 6},
                                {3, 1, 99, 2, 4}};
    int result[SIZE] = {0};
    findMaxVal(result, numbers, 3, NUM_COLS);
    int exp[] = {3, 1, 99, 2, 4};
    for (int i = 0; i < 5; i++) REQUIRE(result[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Edge cases — single-row matrix and uniform-value matrix
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: single-row matrix — every function returns that row / its values", "[T4]")
{
    int numbers[1][NUM_COLS] = {{3, 8, 1, 4, 6}};
    int rs[SIZE] = {0}, re[SIZE] = {0}, rv[SIZE] = {0};
    findMaxSum(rs, numbers, 1, NUM_COLS);
    findMaxElm(re, numbers, 1, NUM_COLS);
    findMaxVal(rv, numbers, 1, NUM_COLS);
    int exp[] = {3, 8, 1, 4, 6};
    for (int i = 0; i < 5; i++) REQUIRE(rs[i] == exp[i]);
    REQUIRE(re[0] == 8);
    for (int i = 0; i < 5; i++) REQUIRE(rv[i] == exp[i]);
}

TEST_CASE("T4b: uniform matrix (all 7) — sum/max picks row 0; per-row max all 7", "[T4]")
{
    int numbers[3][NUM_COLS] = {{7, 7, 7, 7, 7},
                                {7, 7, 7, 7, 7},
                                {7, 7, 7, 7, 7}};
    int rs[SIZE] = {0}, re[SIZE] = {0}, rv[SIZE] = {0};
    findMaxSum(rs, numbers, 3, NUM_COLS);
    findMaxElm(re, numbers, 3, NUM_COLS);
    findMaxVal(rv, numbers, 3, NUM_COLS);
    for (int i = 0; i < 5; i++) REQUIRE(rs[i] == 7);
    for (int i = 0; i < 3; i++) REQUIRE(re[i] == 7);
    for (int i = 0; i < 5; i++) REQUIRE(rv[i] == 7);
}
